apiVersion: v1
kind: Pod
metadata:
  name: www-pod
spec:
  containers:
  - name: container-in-www-pod
    #image: quay.io/k8s-arya/simple-echo-server:v1
    image: quay.io/k8s-arya/simple-webapp:v1
    ports:
    - containerPort: 8080
