apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleservice-deploy
spec:
  replicas: 2
  selector:
   matchLabels:
    app: simpleservice
  template:
    metadata:
      labels:
        app: simpleservice
    spec:
      containers:
      - name: simpleservice
        image: quay.io/k8s-arya/simple-webapp:v2
        ports:
        - containerPort: 8080
        env:
        - name: SIMPLE_SERVICE_VERSION
          value: "2.0"
