apiVersion:   v1
kind:         Pod
metadata:
  name:       jump-pod
spec:
  containers:
  - name:     jump-pod-container
    image:    docker.io/centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
