apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-hpa-demo
spec:
  replicas: 2
  selector:
   matchLabels:
    app: php-apache-hpa
  template:
    metadata:
      labels:
        app: php-apache-hpa
    spec:
      containers:
      - name: php-apache-hpa
        image: gcr.io/google_containers/hpa-example
        ports:
        - containerPort: 80
        resources:
           requests:
              memory: "200Mi"
              cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: php-apache-hpa-svc
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
  selector:
    name: php-apache-hpa

