apiVersion: v1
kind: Pod
metadata:
  name: twocontainers
spec:
  containers:
  - name: simpelsrv
    image: quay.io/k8s-arya/simple-echo-server:v1
    ports:
    - containerPort: 9876
  - name: shell
    image: docker.io/centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
