apiVersion: v1
kind: ReplicationController
metadata:
  name: rcex
spec:
  replicas: 1
  selector:
    app: sise
  template:
    metadata:
      name: somename
      labels:
        app: sise
    spec:
      containers:
      - name: sise
        image: quay.io/k8s-arya/simple-echo-server:v1
        ports:
        - containerPort: 9876
