apiVersion: v1
kind: Pod
metadata:
  name: consume-secret
spec:
  containers:
  - name: my-application
    image: docker.io/centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    volumeMounts:
      - name: apitokenvol
        mountPath: "/tmp/apitoken"
        readOnly: true
  volumes:
  - name: apitokenvol
    secret:
      secretName: apitoken
