apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
spec:
  replicas: 2
  selector:
   matchLabels:
    app: simpleservice
  template:
    metadata:
      labels:
        app: simpleservice
    spec:
      containers:
      - name: my-simple-webapp
        image: quay.io/k8s-arya/simple-webapp:v11
        ports:
        - containerPort: 8080
        env:
        - name: SIMPLE_SERVICE_VERSION
          value: "1.0"
        resources:
           requests:
              memory: "50Mi"
              cpu: "50m"
           limits:
              memory: "64Mi"
              cpu: "100m"
      nodeSelector:
         nodetype: prod
     

