apiVersion: v1
kind: Pod
metadata:
  name: my-website1
spec:
  volumes:
  - name: www
  containers:
  - name: website1-container
    image: nginx
    volumeMounts:
    - name: www
      mountPath: /usr/share/nginx/html/
  initContainers:
  - name: clone-from-git-init-container
    image: alpine
    command: [ "sh", "-c", "apk add --no-cache git && git clone https://github.com/lmammino/sample-web-project.git /www" ]
    volumeMounts:
    - name: www
      mountPath: /www/
