apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-prod-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "blue"
        effect: "NoExecute"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - blue
      containers:
      - name: blue-prod-app-pod
        image: docker.io/library/nginx:1.27.5
        ports:
        - containerPort: 80
