apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - key: "LabKeyNode2"
        operator: "Equal"
        value: "LabValueNode2"
        effect: "NoSchedule"
      containers:
      - name: nginx
        image: docker.io/library/nginx:1.27.5
        ports:
        - containerPort: 80
