apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-home-pages
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
