apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-website-deployment
spec:
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
      - name: nginx-website-pod
        image: docker.io/library/nginx:1.27.5
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-storage
        ports:
        - containerPort: 80
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-home-pages 
