
apiVersion: v1
kind: Pod
metadata:
  name: init-containers-simple
  labels:
    app: init-containers-demo
spec:
  containers:
  - name: my-main-container
    image: docker.io/library/busybox:1.37.0
    command: ['/bin/sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-container-10-seconds
    image: docker.io/library/busybox:1.37.0
    command: ['/bin/sh', '-c', "echo Started init-container-10-seconds...; sleep 10; echo done with init-container-10-seconds..."]
  - name: init-container-another-20-seconds
    image: docker.io/library/busybox:1.37.0
    command: ['/bin/sh', '-c', "echo Started init-container-another-20-seconds...; sleep 10; echo done with init-container-another-20-seconds..."]

