
apiVersion: v1
kind: Pod
metadata:
  name: my-website1
spec:
  volumes:
  - name: www
  containers:
  - name: website1-container
    #image: nginx
    image: docker.io/library/nginx:1.27.5
    volumeMounts:
    - name: www
      mountPath: /usr/share/nginx/html/
  initContainers:
  - name: clone-from-git-init-container
    image: docker.io/library/alpine:3.21.3
    command: [ "/bin/sh", "-c", "apk add --no-cache git && git clone https://github.com/octocat/Spoon-Knife /www" ]
    volumeMounts:
    - name: www
      mountPath: /www/


