apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manage-pods
subjects:
- kind: User
  name: "Ravi Kumar"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: manage-pods
  apiGroup: rbac.authorization.k8s.io
